# Generated by Django 4.2.7 on 2024-01-02 05:39

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_order_date_month_order_date_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_month",
            field=models.IntegerField(
                blank=True, null=True, validators=[user.models.validate_month]
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="date_year",
            field=models.IntegerField(
                blank=True, null=True, validators=[user.models.validate_year]
            ),
        ),
    ]
