# Generated by Django 4.2.7 on 2024-01-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_order_date_month_alter_order_date_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestModL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=80, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
