# Generated by Django 4.2.7 on 2024-08-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_testmodl"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="interval",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
