# Generated by Django 4.2.7 on 2024-08-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_order_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="new",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
