# Generated by Django 4.2.7 on 2024-08-29 06:57

from django.db import migrations, models



class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_order_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="new",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
