# Generated by Django 4.2.7 on 2024-08-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_alter_order_new"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="new",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
