# Generated by Django 4.2.7 on 2024-08-29 09:14

from django.db import migrations, models




class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_alter_order_new"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="new_int",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="new",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
