# Generated by Django 4.2.7 on 2024-08-29 09:36

from django.db import migrations, models

from datetime import timedelta
import re


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0014_alter_order_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="interval",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
